# Usamos la imagen oficial de Python 3
FROM python:3.12-slim

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar tu script al contenedor
COPY banco.py .

# Comando por defecto para ejecutar el script
CMD ["python3", "banco.py"]
